version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: alanbarros-keeweb_web_1
      APP_PORT: 443
      PROXY_AUTH_ADD: 'false'
      PROXY_HTTPS: 'true'       # <--- Certifica que requests de proxy para o backend sÃ£o via HTTPS
    container_name: alanbarros-keeweb_app_proxy_1
    
  web:
    container_name: alanbarros-keeweb_web_1
    image: ghcr.io/keeweb/keeweb:latest       # Github image
  # image: keeweb/keeweb:latest               # Dockerhub image
    restart: unless-stopped
    volumes:
        - ${APP_DATA_DIR}/keeweb:/config
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
