version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: alanbarros-keeweb_web_1
      APP_PORT: 8031

  web:
    container_name: keeweb
    image: ghcr.io/keeweb/keeweb:latest       # Github image
  # image: keeweb/keeweb:latest               # Dockerhub image
    restart: unless-stopped
    ports:
        - "4431:443"
        - "8031:80"
    volumes:
        - ${APP_DATA_DIR}/keeweb:/config
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC