version: "3.7"
services:
  rtsp-to-web:
    image: ghcr.io/deepch/rtsptoweb:latest
    container_name: alanbarros-rtsptoweb_web_1
    network_mode: "host"
    #volumes:
    # Descomente e ajuste o caminho caso queira usar um arquivo de configuração personalizado
    # - ./config.json:/config/config.json
    restart: unless-stopped
    #environment:
    # Adicione variáveis de ambiente aqui, se necessário
    # Exemplo: DEBUG=true
